---
title: Cloud4est - Innovational hub | Self-developer community | Innovációs csomópont | Önfejlesztő közösség
timezone: Europe/Budapest
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: nestgrouphu@gmail.com
description: Innovational hub | Self-developer community | Innovációs csomópont | Önfejlesztő közösség
logo: /assets/images/CD4ST_logo.svg
social:
  links:
    - https://www.facebook.com/CD4ST
    - https://twitter.com/CD4ST
    - https://www.instagram.com/cloud4st/
    - https://www.youtube.com/channel/UC1aBUmUZTGBWwj5N9ktfx7w
    - https://github.com/Cloud4est/
    - https://www.linkedin.com/company/cloud4est/
baseurl:
url: https://cloud4est.github.io
author:
facebook_url: https://www.facebook.com/CD4ST
github_url: https://github.com/Cloud4est/
instagram_url: https://www.instagram.com/cloud4st/
twitter_url: https://twitter.com/CD4ST
youtube_url: https://www.youtube.com/channel/UC1aBUmUZTGBWwj5N9ktfx7w
linkedin_url: https://www.linkedin.com/company/cloud4est/
include:
- _pages
markdown: kramdown
style: compressed
